# Generated by Django 5.0.3 on 2024-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('category', models.TextField()),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
